---
- name: to uninstall httpd & apache pkg
  hosts: all
  become: true
  tasks:
  - name: to stop httpd
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: to uninstall httpd 
    yum: 
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"

  - name: to stop apache2
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"
 
  - name: to uninstall apache2
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
